server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
      spring:
          framework: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
      static-locations:
        - classpath:/static/
        - classpath:/public/
  application:
    name: astroMood
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB}?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID_KEY}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URL}

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration_time: 86400000 #1일
cloud:
  aws:
    s3:
      buckets:
        bucket1:
          name: astro-mood-profile
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false